CollectOrganizer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Base links:
    url(r'^$', 'CollectOrganizer.views.home', name='home'),
    url(r'^about$', 'CollectOrganizer.views.about', name='about'),
    url(r'^admins$', 'CollectOrganizer.views.admin', name='admin'),
    url(r'^na$', 'CollectOrganizer.views.not_available', name='N/A'),
    # admin shortcut
    url(r'^admin/', include(admin.site.urls)),
    # app links
    url(r'^configs/', include('configs.urls', namespace='configs')),
)

configs/urls.py
from django.conf.urls import patterns, include, url
from configs import views


urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^navigator/$', views.navigator, name='navigator'),
)

configs/models.py
from django.db import models


class LibraryPath(models.Model):
    """Defines the db for storing HDD paths for importing Media Collection"""
    media_path = models.CharField(max_length=500)
    media_type = models.CharField(max_length=100)

    class Meta:
        unique_together = ['media_type', 'media_path']

    def __str__(self):
        return self.media_type + " : " + self.media_path

configs/forms.py
from django import forms

from configs.models import LibraryPath


class LibraryPathForm(forms.ModelForm):
    """Auto django model form"""
    class Meta(object):
        model = LibraryPath
        fields = ['media_type', 'media_path']

CollectOrganizer/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def home(request, **kwargs):
    """The Landing page"""
    return render(request, 'CollectOrganizer/index.html')


def about(request, **kwargs):
    """About the product"""
    return render(request, 'CollectOrganizer/about.html')


def not_available(request, **kwargs):
    """Future implementations"""
    return render(request, 'CollectOrganizer/unavailable.html')


def admin(request, **kwargs):
    """Easy access to django admin"""
    return render(request, 'CollectOrganizer/admin.html')

configs/views.py
from django.shortcuts import render
from models import LibraryPath
from forms import LibraryPathForm


# Create your views here.
def index(request, **kwargs):

    paths = LibraryPath.objects.all()

    context = {'paths': paths}

    return render(request, 'configs/index.html', context)


def navigator(request, **kwargs):
    """Computer disk navigator and path saving functionality"""
    import os
    import psutil
    from django.contrib import messages

    destination = ''
    dirs = []
    files = []

    if request.method == 'POST':
        # create a form instance and populate it with data from the request
        form = LibraryPathForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Successfully added the path. It would be used for importing media into Collection.')
        else:
            messages.add_message(request, messages.INFO, 'Could not add the path. Already exists.')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = LibraryPathForm()

    drives = [each.mountpoint for each in psutil.disk_partitions() if 'fixed' in each.opts]

    if request.GET.get('dir'):
        destination = request.GET.get('dir')
        try:
            os.chdir(destination)
        except Exception as e:
            messages.add_message(request, messages.WARNING, "Access Denied")

        dirs = [each for each in os.listdir(os.getcwd()) if os.path.isdir(each)]
        files = [each for each in os.listdir(os.getcwd()) if os.path.isfile(each)]
        current = os.getcwd()
    else:
        current = 'Computer Root'

    context = {'parent': destination, 'current': current, 'drives': drives, 'dirs': dirs, 'files': files, 'form': form}

    return render(request, 'configs/navigator.html', context)

configs/templates/configs/index.html
{% extends 'CollectOrganizer/base.html' %}

{% block title %}Library Paths{% endblock %}

{% load static %}

{% block content %}
    <div class="jumbotron">
        <h3 class="breadcrumb modal-header text-center"><span class="glyphicon glyphicon-th-list"> Drives</span></h3>
        {% if paths %}
            <table id="paths_table" class="table"></table>
        {% else %}
            <p class="popover-content text-warning"><span class="glyphicon glyphicon-warning-sign"> No path added to Collections</span></p>
        {% endif %}
    </div>

    <script type="text/javascript">
        $(document).ready(function(){
            var $table = '#paths_table';

            var data = [];

            //define common ajax object for addition, update and delete.
            var ajaxObj = {
                dataType: "JSON",
                beforeSend: function () {
                    this.pqGrid("showLoading");
                },
                complete: function () {
                    this.pqGrid("hideLoading");
                },
                error: function () {
                    this.pqGrid("rollback");
                }
            };

            //called by delete button.
            function deleteRow(rowIndx, $grid) {
                $grid.pqGrid("addClass", { rowIndx: rowIndx, cls: 'pq-row-delete' });
                var rowData = $grid.pqGrid("getRowData", { rowIndx: rowIndx });
                var ans = window.confirm("Are you sure to delete row No " + (rowIndx + 1) + "?");

                if (ans) {
                    $grid.pqGrid("deleteRow", { rowIndx: rowIndx, effect: true });

                    var PathId = $grid.pqGrid("getRecId", { rowIndx: rowIndx });

                    $.ajax($.extend({}, ajaxObj, {
                        context: $grid,
                        url: "/configs/navigator/delete",
                        data: { path_id: PathId },
                        success: function () {
                            $grid.pqGrid("commit");
                            $grid.pqGrid("refreshDataAndView");
                        },
                        error: function () {
                            //debugger;
                            $grid.pqGrid("removeClass", { rowData: rowData, cls: 'pq-row-delete' });
                            $grid.pqGrid("rollback");
                        }
                    }));
                }
                else {
                    $grid.pqGrid("removeClass", { rowIndx: rowIndx, cls: 'pq-row-delete' });
                }
            }

            var grid = {
                width: 800,
                height: 500,
                title: "Library",
                resizable: true,
                collapsible: false,
                filterModel: { on: true, mode: "AND", header: true },
                editable: false,
                //use refresh event to display jQueryUI buttons and bind events.
                refresh: function () {
                    //debugger;
                    var $grid = $(this);
                    if (!$grid) {
                        return;
                    }
                    //delete button
                    $grid.find("button.delete_btn").button({ icons: { primary: 'ui-icon-close'} }).unbind("click").bind("click", function (evt) {
                        var $tr = $(this).closest("tr");
                        var rowIndx = $grid.pqGrid("getRowIndx", { $tr: $tr }).rowIndx;
                        alert(rowIndx);
                        deleteRow(rowIndx, $grid);
                    });
                }
            };

            grid.colModel = [
                {
                    title: "Path ID",
                    dataType: "integer",
                    dataIndx: "PathID",
                    hidden: true
                },
                {
                    title: "Media Type",
                    width: 200,
                    dataType: "string",
                    filter: { type: "select",
                        condition: 'equal',
                        prepend: { '': '--Select--' },
                        options: [
                            {
                                "movies":"Movies",
                                "tvseries":"TV Series",
                                "toons":"Cartoons",
                                "music":"Music",
                                "books":"Books",
                                "comics":"Comics"
                            }
                        ],
                        listeners: ['change']
                    }
                },
                {
                    title: "Media Path",
                    width: 500,
                    dataType: "string"
                },
                {
                    title: "",
                    editable: false,
                    minWidth: 50,
                    sortable: false,
                    render: function (ui) {
                        return "<button type='button' class='delete_btn'>Delete</button>";
                    }
                }
            ];

            {% for path in paths %}
                data.push(["{{ path.id }}", "{{ path.media_type | title }}", "{{ path.media_path | escapejs }}"]);
            {% endfor %}

            grid.dataModel = { data: data };

            $($table).pqGrid(grid);
            $($table).pqGrid("option", "pageModel.type", "local");
            $($table).pqGrid("refreshView");

        });
    </script>
{% endblock content %}

configs/templates/configs/navigator.html
{% extends 'CollectOrganizer/base.html' %}

{% block title%}- Add Library{% endblock %}

{% block content %}
    <form action="{% url 'configs:navigator' %}" method="post" class="form-inline">
        {% csrf_token %}
        <fieldset>
            <legend>Navigate to a path and Add as source for the following media type:</legend>
            <label>Path:&nbsp;&nbsp;</label><label class="panel popover-title">{{ current }}</label>
            <input name="media_path" value="{{ current }}" type="hidden"/>
            <br/>
            <br/>
            <label>Media Type: </label>
            <select name="media_type" class="form-control">
                <option value="movies">Movies</option>
                <option value="tvseries">TV Series</option>
                <option value="toons">Cartoons</option>
                <option value="music">Music</option>
                <option value="books">Books</option>
                <option value="comics">Comics</option>
            </select>
            <br/>
            <br/>
            <input type="submit" value="Add" class="form-control btn-danger"/>
        </fieldset>
    </form>
    <br/>

    {% if messages %}
    <div class="">
        <ul class="list-group">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <li class="list-group list-group-item list-group-item-heading list-group-item-warning"><b><span class="glyphicon glyphicon-flash"></span> {{ message }}</b></li>
            {% endif %}
        {% endfor %}
        </ul>
    </div>
    {% endif %}


    <div class="jumbotron">
        <p class="panel popover-title text-center"><span class="glyphicon glyphicon glyphicon-search"></span> Directory Explorer</p>

        {% if request.GET.dir %}
            {% if current in drives %}
                <a href="{% url 'configs:navigator' %}"><h2 class="fa fa-arrow-circle-left"> Back</h2></a>
            {% else %}
                <a href="{% url 'configs:navigator' %}?dir=.."><h2 class="fa fa-arrow-circle-left"> Back</h2></a>
            {% endif %}
            <span>&NonBreakingSpace;&NonBreakingSpace;&NonBreakingSpace;&NonBreakingSpace;&NonBreakingSpace;&NonBreakingSpace;</span>
            <a href="{% url 'configs:navigator' %}"><h2 class="fa fa-desktop"> Computer</h2></a>
        {% else %}
            <h2 class="fa fa-desktop"> Computer</h2>
        {% endif %}

        <div class="row">
            <p class="col-lg-2 col-md-2 col-sm-2 text-right address">Address</p>
            <p class="panel modal-title col-lg-10 col-md-10 col-sm-10 col-xs-12">{{ current }}</p>
        </div>
        <hr/>

        {% if not dirs and not files and not parent %}
            {% for each in drives %}
                <a href="{% url 'configs:navigator' %}?dir={{ each|urlencode }}"><p class="glyphicon glyphicon-hdd"> {{ each }}</p>
                </a><br/>
            {% endfor %}
            <hr/>
        {% endif %}

        {% if messages %}
            <div class="">
                <ul class="list-group">
                    {% for message in messages %}
                        {% if message.tags == 'warning' %}
                            <li class="list-group list-group-item list-group-item-heading list-group-item-warning">
                                <b><span class="glyphicon glyphicon-flash"></span> {{ message }}</b></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if dirs %}
            <p><b><i>Folders</i></b></p>
            {% for each in dirs %}
                <a href="{% url 'configs:navigator' %}?dir={{ each|urlencode }}"><p class="glyphicon glyphicon-folder-open"> {{ each }}</p></a><br/>
            {% endfor %}
            <hr/>
        {% endif %}

        {% if files %}
            <p><b><i>Files</i></b></p>
            {% for each in files %}
                <span class="glyphicon glyphicon-file"> {{ each }}</span><br/>
            {% endfor %}
            <hr/>
        {% endif %}
    </div>
{% endblock content %}

templates/CollectOrganizer/about.html
{% extends 'CollectOrganizer/base.html' %}

{% block title%}- About{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1>About the software</h1>
        <blockquote>
            <p>Created by HZ.</p>
            <p>The following features are added.</p>
            <ul>
                <li>Cataloguing and organizing Movies, TV Shows, Cartoon Series in collection</li>
                <li>Give the path to the root of Movies/TV shows/Cartoons and it automatically acquires the proper info</li>
                <li>Ability to manually add or modify the info.</li>
                <li>Keeps record of entries not obtained automatically.</li>
            </ul>
        </blockquote>

    </div>
{% endblock content %}

templates/CollectOrganizer/admin.html
{% extends 'CollectOrganizer/base.html' %}

{% block title%}- Admin{% endblock %}

{% block content %}
    <div class="jumbotron">
        <iframe src="/admin/" width="100%" height="500"></iframe>
    </div>
{% endblock content %}

templates/CollectOrganizer/base.html
<!DOCTYPE html>

<html>
	<head>
		<title>Collection {% block title %}{% endblock %}</title>

        <!--Add BootStrap-->
        <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		{% load staticfiles %}

        {% block css %}
        <!-- compiled and minified CSS JS -->
        <link rel="stylesheet" type="text/css" href="{% static 'CollectOrganizer/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'CollectOrganizer/css/font-awesome.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'CollectOrganizer/css/jquery-ui.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'CollectOrganizer/css/jquery.ui.theme.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'CollectOrganizer/css/pqgrid.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'CollectOrganizer/themes/Office/pqgrid.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'CollectOrganizer/css/custom.css' %}"/>
        {% endblock css %}

        {% block js %}
        <script src="{% static 'CollectOrganizer/js/jquery.min.js' %}"></script>
        <script src="{% static 'CollectOrganizer/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'CollectOrganizer/js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'CollectOrganizer/js/pqgrid.min.js' %}"></script>
        {% endblock js %}
	</head>
	
	<body>

        <div id="container" class="container-fluid">
            <div class="rect1"></div>
            <!-- Static header navbar -->
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'CollectOrganizer.views.home' %}">HZ's Collection Organizer</a>
                    </div>

                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'CollectOrganizer.views.home' %}"><button type="button" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</button></a></li>

                            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><button type="button" class="btn btn-lg btn-info"><span class="glyphicon glyphicon-gift" aria-hidden="true"></span> Collection <span class="caret"></span></button></a>

                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'CollectOrganizer.views.not_available' %}"><span class="glyphicon glyphicon-film" aria-hidden="true"></span> Movies</a></li>
                                    <li><a href="{% url 'CollectOrganizer.views.not_available' %}"><img src="{% static 'CollectOrganizer/imgs/tv.png' %}"/> TV Series</a></li>
                                    <li><a href="{% url 'CollectOrganizer.views.not_available' %}"><img src="{% static 'CollectOrganizer/imgs/tf.png' %}"/> Cartoons</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Others</li>
                                    <li><a href="{% url 'CollectOrganizer.views.not_available' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span> Music</a></li>
                                    <li><a href="{% url 'CollectOrganizer.views.not_available' %}"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Books</a></li>
                                </ul>
                            </li>
                            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><button type="button" class="btn btn-lg btn-warning"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Settings <span class="caret"></span></button></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'configs:navigator' %}"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add Library Path</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">List</li>
                                    <li><a href="{% url 'configs:index' %}"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Manage Library Paths</a></li>

                                    <li class="divider"></li>
                                    <li class="dropdown-header">Admin Panel</li>
                                    <li><a href="{% url 'CollectOrganizer.views.admin' %}"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Administration</a></li>
                                </ul>
                            </li>

                            <li><a href="{% url 'CollectOrganizer.views.about' %}"><button type="button" class="btn btn-lg btn-danger"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> About</button></a></li>

                        </ul>

                    </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </nav>

            <!-- Content -->
            {% block content %}

            {% endblock content %}
            <!-- content end -->

            <!-- footer -->
            <div class="row">
                <div class="col-lg-1 col-md-2 col-sm-2 col-xs-4">&copy 2016 HZ</div>
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-6">Powered by django</div>
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-2">Help</div>
            </div>
            <!-- footer end -->
        </div>
	</body>
</html>

templates/CollectOrganizer/index.html
{% extends 'CollectOrganizer/base.html' %}

{% block title%}- Main page{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>HZ's Collection Organizer</h1>
    <blockquote>
        <p>A tool for organizing digital collection of media, e.g. Movies, TV shows, Cartoon Series. Also Music, Books and other types of Collectables are kept in todo list.</p>
    </blockquote>
    <p>
        <a class="btn btn-lg btn-primary" href="{% url 'CollectOrganizer.views.about' %}" role="button">View Software Features &raquo;</a>
    </p>
</div>
{% endblock content %}

templates/CollectOrganizer/unavailable.html
{% extends 'CollectOrganizer/base.html' %}

{% block title%}- Not Available{% endblock %}

{% block content %}
    <div class="jumbotron">
        <strong>This portion is not implemented yet.</strong>
    </div>
{% endblock content %}